Repository thm-mni-ii/digital-classroom, pull requests merged in 2021-09, with the labels that each got.

#18 [CI/CD] Improve Docker development
  .github/workflows/docker-image.yml
Labels: CI/CD, Docker

#29 update env variables in docker-compose.yml
  docker-compose.yml
  examples/docker-compose/docker-compose.yml
Labels: Docker

#33 [CI/CD] Fix test-system deployment
  .github/workflows/docker-image.yml
  examples/deployment/restart-classroom.sh
Labels: CI/CD

#39 Fix attendee xml data in getMeeting & getMeetingInfo
  src/main/kotlin/de/thm/mni/ii/classroom/model/api/Attendees.kt
  src/main/kotlin/de/thm/mni/ii/classroom/model/api/GetMeetingsBBBResponse.kt
  src/main/kotlin/de/thm/mni/ii/classroom/model/api/MeetingInfoBBBResponse.kt
Labels: bug

#68 [CI/CD] Build program at each pull request
  .github/workflows/deploy-test-system.yml
  .github/workflows/docker-image.yml
Labels: CI/CD
